# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# Aliases allow you to create nicknames for gh commands
aliases:
    ssia: |
        !gh issue create --title "$(eval 'echo $@')" --body "SSIA"
    patch: '!echo ''{"ref":"''$(git symbolic-ref refs/remotes/origin/HEAD | awk -F''/'' ''{print $NF}'')''","inputs":{"method":"patch"}}'' | gh api -X POST repos/:owner/:repo/actions/workflows/release.yaml/dispatches --input -'
    last: |
      !gh browse "$(git rev-parse HEAD)" $@
    me: api user --jq .login
    topic: api "search/repositories?q=topic:$1%20fork:true" --jq ".items[].full_name" --paginate
    issue mine: issue list --assignee @me
    pr mine: pr list --assignee @me
version: "1"
