#!/bin/zsh

if [ -z "${NVIM_PROXY_URL}" ]; then
  echo "NVIM_PROXY_URL is not set, skipping pre-commit check"
  exit 0
fi

if [ -z "${NVIM_PID}" ]; then
  echo "NVIM_PID is not set, skipping pre-commit check"
  exit 0
fi

if [ -t 0 ]; then
  :
else
  echo "No tty detected, skipping pre-commit check"
  exit 0
fi

exec < /dev/tty
dir="$(git rev-parse --show-toplevel)"
payload="$(jq -n --arg dir "${dir}" '{
  dir: $dir
}')"

# Timeout : 5s
response="$(curl -XPOST -sSL --max-time 5 -H "X-Nvim-Pid: ${NVIM_PID}" \
  -w '\n%{http_code}' "${NVIM_PROXY_URL}/dirty-bufs" -d "${payload}" 2>/dev/null)"
curl_exit_code=$?
http_code="${response##*$'\n'}"
ret="${response%$'\n'*}"

if [ "${http_code}" = "404" ]; then
  exit 0
fi

case "${ret}" in
  "ok")
    : # noop
    ;;
  *)
    echo "Commit cancelled: unsaved buffers detected (${curl_exit_code}:${http_code}: ${ret})"
    exit 1
    ;;
esac
# vim: ft=zsh
