#!/bin/zsh

if [ -n "${PRECOMMIT_ADDRESS}" ]; then
  exec < /dev/tty
  dir="$(git rev-parse --show-toplevel | jq -R)"

  # Timeout : 5s
  ret="$(curl -XPOST -sSL --max-time 5 "${PRECOMMIT_ADDRESS}" -d '{"dir":'"${dir}"'}' 2>/dev/null)"
  curl_exit_code=$?

  case "${ret}" in
    "ok")
      : # noop
      ;;
    *)
      echo "Commit cancelled: unsaved buffers detected (${curl_exit_code}: ${ret})"
      exit 1
      ;;
  esac
fi
# vim: ft=zsh
