[ddu-source]
prefix = "ddusource"
body = """
import type {} from "jsr:@denops/std@~7.3.2";
import { BaseSource, type GatherArguments } from "jsr:@shougo/ddu-vim@~7.0.0/source";
import type { Item} from "jsr:@shougo/ddu-vim@~7.0.0/types";

type ActionData = Record<PropertyKey, never>;

type Params = Record<PropertyKey, never>;

export class Source extends BaseSource<Params, ActionData> {
  override kind = "";

  override gather(
    args: GatherArguments<Params>,
  ): ReadableStream<Item<ActionData>[]> {
    throw new Error("not implemented");
  }

  override params(): Params {
    return {};
  }
}"""
