#:schema https://raw.githubusercontent.com/Yash-Singh1/vscode-snippets-json-schema/main/schema.json

[denops-test-boilerplate]
prefix = "denops-test-boilerplate"
body = """
import { test } from "https://deno.land/x/denops_test@v1.6.2/mod.ts";
import { assertEquals } from "https://deno.land/std@~0.223.0/assert/mod.ts";

test({
  mode: "all",
  name: "$1",
  fn: async (denops) => {
    $1
  },
})
"""

[denops-test-one]
prefix = "denops-test-one"
body = """
test({
  mode: "all",
  name: "$1",
  fn: async (denops) => {
    $2
  },
})
"""
