["table driven test function"]
prefix = "testtablefunc"
description = "Snippet for table driven test"
body = """"func Test$1(t *testing.T) {
	for _, testcase := range []struct {
		title string
		$2
	}{
		{
			title: "$3",
			$4
		},
	} {
		t.Run(testcase.title, func(t *testing.T) {
			$0
		})
	}
}"""

["table driven test"]
prefix = "testtable"
description = "Snippet for table driven test"
body = """for _, testcase := range []struct {
		title	string
		$2
	}{
		{
			title: "$3",
			$4
		},
	} {
		t.Run(testcase.title, func(t *testing.T) {
			$0
		})
	}"""

["sub test"]
prefix = "testsub"
description = "Snippet for sub-test"
body = """t.Run("$1", func(t *testing.T) {
	$2
})"""

["test fatal error"]
prefix = "ifterr"
description = "Snippet for fatal error in test"
body = """if err != nil {
	t.Fatal(err)
}"""
