[help-doc]
prefix = "helpdoc"
body = """
*$1.txt*	(description of the plugin)
*$1*

Author: kyoh86 <me@kyoh86.dev>
License: MIT License


==============================================================================
Contents ~                             *$1-contents*

Function         |$1-function|
Option           |$1-option|


==============================================================================
Function ~                             *$1-function*


==============================================================================
Option  ~                              *$1-option*


==============================================================================
"vim:tw=78:ts=8:sw=8:ft=help:norl:noet:fen:
"""

[help-hr]
prefix = "helphr"
body = "=============================================================================="


[help-hr2]
prefix = "helphr2"
body = "------------------------------------------------------------------------------"


[help-header]
prefix = "helpheader"
body = "$1 ~"


[help-tag]
prefix = "helptag"
body = " *$1* "


[help-link]
prefix = "helplink"
body = " |$1| "
