[help-doc]
prefix = "helpdoc"
body = """
$1.txt	(description of the plugin)

Author: kyoh86 <me@kyoh86.dev>
License: MIT License


==============================================================================
CONTENTS ~                             *$1-contents*

Introduction     |$1-introdution|
Function         |$1-function|


==============================================================================
FUNCTION                               *$1-function*


==============================================================================
OPTIONS ~                              *$1-function*


==============================================================================
"vim:tw=78:ts=8:sw=8:ft=help:norl:noet:fen:
"""

[help-hr]
prefix = "helphr"
body = "=============================================================================="


[help-header]
prefix = "helpheader"
body = "$1 ~"


[help-tag]
prefix = "helptag"
body = " *$1* "


[help-link]
prefix = "helplink"
body = " |$1| "
