#:schema https://raw.githubusercontent.com/Yash-Singh1/vscode-snippets-json-schema/main/schema.json

["Vim plugin issue"]
prefix = "vim.plugin.issue"
description = "Vim plugin issue"
body = """
## Description

$1

## Steps to Reproduce

1. $2

## Expected Behavior

## Actual Behavior

## Environment Information

- OS: ${VIM:v:lua.vim.uv.os_uname().sysname}
- Neovim: ${VIM:luaeval("tostring(vim.version())")}

## Vimrc

```vim
$0
```
"""

["Vim version"]
prefix = "vim.version"
description = "Vim version"
body = "${VIM:luaeval('tostring(vim.version())')}"
