["lazy.nvim spec"]
prefix = "lazyspec"
description = "Snippet for lazy.nvim spec"
body = """
---@type LazySpec
local spec = {
  \"$1\",
  $2
}
return spec"""

["lazy.nvim specs"]
prefix = "lazyspecs"
description = "Snippet for lazy.nvim specs"
body = """
---@type LazySpec[]
local spec = {{
  \"$1\",
  $2
}}
return spec"""

["Neovim autoload functions call"]
prefix = "vimfa"
description = "Call vim autoload functions call"
body = """
vim.fn["$1"]($2)"""
