vim.opt.errorformat = {
  '%*[^"]"%f"%*\\D%l: %m',
  '"%f"%*\\D%l: %m',
  "%-Gg%\\?make[%*\\d]: *** [%f:%l:%m",
  "%-Gg%\\?make: *** [%f:%l:%m",
  "%-G%f:%l: (Each undeclared identifier is reported only once",
  "%-G%f:%l: for each function it appears in.)",
  "%-GIn file included from %f:%l:%c:",
  "%-GIn file included from %f:%l:%c",
  "%-GIn file included from %f:%l",
  "%-G%*[ ]from %f:%l:%c",
  "%-G%*[ ]from %f:%l:",
  "%-G%*[ ]from %f:%l",
  "%f:%l:%c:%m",
  "%f(%l):%m",
  "%f:%l:%m",
  " line %l%*\\D%c%*[^ ] %m",
  "%D%*\\a[%*\\d]: Entering directory %*[`']%f'",
  "%X%*\\a[%*\\d]: Leaving directory %*[`']%f'",
  "%D%*\\a: Entering directory %*[`']%f'",
  "%X%*\\a: Leaving directory %*[`']%f'",
  "%DMaking %*\\a in %f",
  "%f|%l| %m",
  "%-G%.%#",
}
