#!/bin/bash

apt_install() {
  # Common Utilities
  sudo apt install --yes \
      diffutils \
      dnsutils  \
      findutils \
      unzip     \
      ripgrep   \
      git       \
      cmake

    # Shell environment
  sudo apt install --yes \
      zsh \
      zsh-autosuggestions \
      zsh-syntax-highlighting

  # Lua
  sudo apt install --yes \
      luajit \
      luarocks

  # Development Environment
  sudo apt install --yes \
      telnet  \
      tidy    \
      man-db  \
      tig     \
      make    \
      cmake   \
      wslu    \
      rsync   \
      inotify-tools \
      coreutils \
      binutils \
      gettext

  # To Mount NAS
  sudo apt install --yes \
    cifs-utils

  # To convert movies
  sudo apt install --yes \
    ffmpeg

  # for git send-email
  sudo apt install --yes  \
    git-email             \
    libio-socket-ssl-perl \
    libauthen-sasl-perl

  # ngrok
  curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
    | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
    && echo "deb https://ngrok-agent.s3.amazonaws.com bookworm main" \
    | sudo tee /etc/apt/sources.list.d/ngrok.list \
    && sudo apt update \
    && sudo apt install ngrok
}

apt_install
