#!/bin/bash

setup_apt_locale() {
  # Library
  sudo apt install --yes \
      language-pack-ja \
      language-pack-en

  # Set locale
  sudo localedef -i /usr/share/i18n/locales/ja_JP -f UTF-8 /usr/lib/locale/ja_JP.UTF-8
  sudo localedef -i /usr/share/i18n/locales/en_US -f UTF-8 /usr/lib/locale/en_US.UTF-8
  sudo localedef --add-to-archive /usr/lib/locale/ja_JP.UTF-8 || :
  sudo localedef --add-to-archive /usr/lib/locale/en_US.UTF-8 || :
  sudo localectl set-locale LANG=ja_JP.UTF-8
  source /etc/locale.conf
}

setup_apt_locale
