#!/bin/bash

# Clone dotfiles
clone_dotfiles() {

  DOTFILES_DIR="${HOME}/Projects/github.com/kyoh86/dotfiles"
  DOTFILES_WORKTREE="${DOTFILES_DIR}/.worktree/main"
  [ -d "${DOTFILES_DIR}" ] || git clone --bare https://github.com/kyoh86/dotfiles "${DOTFILES_DIR}"
  [ -d "${DOTFILES_WORKTREE}" ] || git -C "${DOTFILES_DIR}" worktree add "${DOTFILES_WORKTREE}" main
  rm -rf ~/.config
  ln -s "${DOTFILES_WORKTREE}" ~/.config

  # Add the SSH key to the ssh-agent
  mkdir -p ~/.ssh && echo 'Include ~/.config/ssh/*.conf' >> ~/.ssh/config

  if [ ! -d "${DOTFILES_WORKTREE}/gnupg" ] ; then
    mkdir -p "${DOTFILES_WORKTREE}/gnupg"
  fi
  chmod 700 "${DOTFILES_WORKTREE}/gnupg"
}

clone_dotfiles
