#!/bin/bash

# gordon
install_gordon() {
  export PATH="${PATH}:${HOME}/go/bin:${HOME}/.local/bin"
  go run github.com/kyoh86/gordon@latest install kyoh86/gordon
  go run github.com/kyoh86/gordon@latest restore "${HOME}/.config/gordon/bundle"
  rm -f "${HOME}/go/bin/gordon" || :
}

install_gordon
