#!/bin/bash

install_homebrew() {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"

  brew install \
    diffutils \
    coreutils \
    findutils \
    cmake \
    direnv \
    delta \
    zsh \
    zsh-autosuggestions \
    zsh-syntax-highlighting

  brew install \
    sqlite \
    luajit \
    luarocks \
    actionlint \
    awscli \
    docker-compose \
    gh \
    httpie \
    jq \
    postgresql \
    ripgrep \
    tig \
    unzip \
    git

  brew install \
    inkdrop
}

install_homebrew
