#!/bin/bash

# Neovim
install_neovim() {
  if [ -x "$(command -v nvim)" ]; then
    return;
  fi
  eval "$(luarocks --lua-version=5.1 path)"
  nvim_tmpdir="$(mktemp -d)"
  trap "sudo rm -rf ${nvim_tmpdir}" EXIT
  git clone --depth 1 -b nightly https://github.com/neovim/neovim "$nvim_tmpdir/neovim"
  pushd "$nvim_tmpdir/neovim" || return 1
  make CMAKE_BUILD_TYPE=Release
  sudo make install
  popd || return 1
}

install_neovim
