#!/bin/bash

set -e

# Neovim
install_neovim() {
  eval "$(luarocks --lua-version=5.4 path)"
  nvim_tmpdir="$(mktemp -d)"
  trap "sudo rm -rf ${nvim_tmpdir}" EXIT
  git clone --depth 1 -b nightly https://github.com/neovim/neovim "$nvim_tmpdir/neovim"
  pushd "$nvim_tmpdir/neovim" || return 1
  make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/usr/local"
  sudo make install
  popd || return 1
}

install_neovim
