#!/bin/bash

create_wsl_config() {
  cat - << EOS | sudo tee /etc/wsl.conf
[boot]
systemd=true

[user]
default=kyoh86

[interop]
appendWindowsPath=false
EOS

  cat - << 'EOS' | tee $HOME/.zshenv
export ZDOTDIR="${XDG_CONFIG_HOME:-${HOME}/.config}/zsh"
EOS
}

create_wsl_config
