nmap <buffer> <leader>n <Plug>(github-issue-viewer-next)
nmap <buffer> <leader>p <Plug>(github-issue-viewer-prev)
nmap <buffer> <leader>e <Plug>(github-issue-viewer-edit)
nmap <buffer> <leader>c <Plug>(github-issue-viewer-comment)
nmap <buffer> <leader>b <Plug>(github-issue-viewer-browse)
