vim.api.nvim_buf_create_user_command(0, "DenoUpdate", function()
  vim.cmd([[terminal udd %]])
end, {})
vim.api.nvim_buf_create_user_command(0, "DenoCache", function()
  vim.cmd([[terminal deno cache %]])
end, {})
