set-option -gF @paste_from_nvim_register '#{XDG_CONFIG_HOME}/dotfiles-tool/bin/tmux-paste-from-nvim-register'
set-option -gF @capture_pane_to_nvim '#{XDG_CONFIG_HOME}/dotfiles-tool/bin/tmux-capture-pane-to-nvim'

bind-key y run-shell -b '#{b:@capture_pane_to_nvim}'
bind-key ` run-shell -b '#{b:@capture_pane_to_nvim}'

# paste from Neovim registers
bind-key p run-shell -b '#{b:@paste_from_nvim_register}'
bind-key g switch-client -T paste-registers
# Common registers: " (default/unnamed), + (clipboard), * (selection)
bind-key -T paste-registers p run-shell -b '#{b:@paste_from_nvim_register} "+"'
bind-key -T paste-registers + run-shell -b '#{b:@paste_from_nvim_register} "+"'
bind-key -T paste-registers "*" run-shell -b '#{b:@paste_from_nvim_register} "*"'
bind-key -T paste-registers "0" run-shell -b '#{b:@paste_from_nvim_register} "0"'
bind-key -T paste-registers "1" run-shell -b '#{b:@paste_from_nvim_register} "1"'
bind-key -T paste-registers "2" run-shell -b '#{b:@paste_from_nvim_register} "2"'
bind-key -T paste-registers "3" run-shell -b '#{b:@paste_from_nvim_register} "3"'
bind-key -T paste-registers "4" run-shell -b '#{b:@paste_from_nvim_register} "4"'
bind-key -T paste-registers "5" run-shell -b '#{b:@paste_from_nvim_register} "5"'
bind-key -T paste-registers "6" run-shell -b '#{b:@paste_from_nvim_register} "6"'
bind-key -T paste-registers "7" run-shell -b '#{b:@paste_from_nvim_register} "7"'
bind-key -T paste-registers "8" run-shell -b '#{b:@paste_from_nvim_register} "8"'
bind-key -T paste-registers "9" run-shell -b '#{b:@paste_from_nvim_register} "9"'

# vim:ft=tmux
