set-option -g status on
set-option -g status-style fg=black,bg=brightgreen,bright

set-option -g status-right " #($XDG_CONFIG_HOME/dotfiles-tool/dest/git-status-line #{pane_current_path})"
set-option -g status-left "#[bg=green,fg=brightwhite,bright] #($XDG_CONFIG_HOME/dotfiles-tool/dest/path-shorten #{pane_current_path}) #[default]#[fg=green,bg=brightgreen,bright]\uE0B8#[default]"
set-option -g status-left-length 0

# Hide window-status when only one window
set-option -g window-status-format ""
set-option -g window-status-current-format ""
set-hook -g client-attached 'if-shell "[ #{session_windows} -eq 1 ]" "set-option window-status-format \"\"" "set-option window-status-format \" #I:#W#F \""'
set-hook -g client-attached 'if-shell "[ #{session_windows} -eq 1 ]" "set-option window-status-current-format \"\"" "set-option window-status-current-format \" #I:#W#F \""'
set-hook -g session-window-changed 'if-shell "[ #{session_windows} -eq 1 ]" "set-option window-status-format \"\"" "set-option window-status-format \" #I:#W#F \""'
set-hook -g session-window-changed 'if-shell "[ #{session_windows} -eq 1 ]" "set-option window-status-current-format \"\"" "set-option window-status-current-format \" #I:#W#F \""'

set-option -g pane-border-status off
set-option -g pane-border-lines single
set-option -g pane-border-indicators off
set-option -g pane-border-style fg=brightwhite,bg=black
set-option -g pane-active-border-style fg=brightwhite,bg=black

# vim:ft=tmux
