set-option -g prefix c-q
unbind-key c-b

set-option -ga terminal-overrides ",xterm-256color:Tc"
# set-option -g status off

source-file -F '#{d:current_file}/shell.conf'
source-file -F '#{d:current_file}/pane.conf'
source-file -F '#{d:current_file}/scroll.conf'
source-file -F '#{d:current_file}/status.conf'

# vim:ft=tmux
