set-option -g prefix c-q

set-option -ga terminal-overrides ",xterm-256color:Tc"

bind-key C-w switch-client -T vim-C-W
bind -T vim-C-W C-v split-window -h -c "#{pane_current_path}"
bind -T vim-C-W v split-window -h -c "#{pane_current_path}"
bind -T vim-C-W C-n split-window -v -b -c "#{pane_current_path}"
bind -T vim-C-W n split-window -v -b -c "#{pane_current_path}"
bind -T vim-C-W c kill-pane
bind -T vim-C-W h select-pane -L
bind -T vim-C-W j select-pane -D
bind -T vim-C-W k select-pane -U
bind -T vim-C-W l select-pane -R
