#!/bin/bash

set -ex

install() {
  yay -S --noconfirm --needed $*
}

# Setup DE/DM
install gnome
sudo systemctl enable gdm.service

# setup fonts
install            \
  noto-fonts       \
  noto-fonts-cjk   \
  noto-fonts-emoji \
  noto-fonts-extra \
  ttf-plemoljp-bin

# Setup IME
install             \
  fcitx5-mozc-ut    \
  fcitx5-ut         \
  fcitx5-gtk        \
  mozc-ut           \
  fcitx5-configtool

install    \
  google-chrome
