#!/bin/bash

# Usage: ./darwin.md

set -ex

MODULE="${HOME}/Projects/github.com/kyoh86/dotfiles/.worktree/main/setup/module"

"${MODULE}"/zshenv
"${MODULE}"/github
"${MODULE}"/dotfiles
"${MODULE}"/homebrew
"${MODULE}"/mise

"${MODULE}"/neovim
