#!/bin/bash

# Usage: ./darwin.md

set -ex

MODULE="${HOME}/dev/gh/kyoh86/dotfiles/.wt/main/setup/module"

"${MODULE}"/zshenv
"${MODULE}"/github
"${MODULE}"/dotfiles
"${MODULE}"/homebrew
"${MODULE}"/mise

"${MODULE}"/neovim
"${MODULE}"/codex_remote
"${MODULE}"/claude_code
