#!/bin/bash

# Usage: ./ubuntu24.md

set -ex

MODULE="${HOME}/Projects/github.com/kyoh86/dotfiles/setup/module"

"${MODULE}"/wsl
"${MODULE}"/apt_update
"${MODULE}"/apt_locale
"${MODULE}"/apt_install
"${MODULE}"/nix
"${MODULE}"/github
"${MODULE}"/dotfiles

# sudo groupadd docker # it may be error "groupadd: group 'docker' already exists" because docker AUR creates it. 
sudo usermod -aG docker "${USER}"

"${MODULE}"/neovim
"${MODULE}"/zenhan
"${MODULE}"/gordon

# gordon
export PATH="$PATH:/home/kyoh86/go/bin:/home/kyoh86/.local/bin"
go install github.com/kyoh86/gordon@latest
gordon install kyoh86/gordon
gordon restore ~/.config/gordon/bundle
rm -f ~/go/bin/gordon || :
