--- 補完とスニペットの設定
-- local spec = {
--   {
--     "golang/vscode-go",
--     ft = { "go" },
--   },
--   {
--     "hrsh7th/cmp-nvim-lua",
--     lazy = true,
--   },
--   {
--     "hrsh7th/cmp-nvim-lsp",
--     lazy = true,
--   },
--   {
--     "hrsh7th/cmp-cmdline",
--     lazy = true,
--   },
--   {
--     "hrsh7th/cmp-path",
--     lazy = true,
--   },
--   {
--     "hrsh7th/cmp-vsnip",
--     lazy = true,
--   },
--   {
--     "hrsh7th/vim-vsnip",
--     lazy = true,
--   },
--   {
--     "rafamadriz/friendly-snippets",
--     lazy = true,
--   },
--   {
--     "hrsh7th/nvim-cmp",
--     dependencies = {
--       "vscode-go",
--       "cmp-nvim-lua",
--       "cmp-nvim-lsp",
--       "cmp-cmdline",
--       "cmp-path",
--       "cmp-vsnip",
--       "vim-vsnip",
--       "friendly-snippets",
--     },
--   },
--   {
--     "uga-rosa/cmp-skkeleton",
--     dependencies = { "skkeleton", "nvim-cmp" },
--   },
-- }
-- return spec
return {}
